# Generated by Django 3.1.7 on 2021-06-10 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ace_build', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optimization',
            old_name='keyword',
            new_name='title',
        ),
    ]
