# Generated by Django 3.1.7 on 2021-06-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_build', '0002_auto_20210610_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword_Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
