# Generated by Django 3.1.7 on 2021-07-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_build', '0003_keyword_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
