# Generated by Django 3.1.7 on 2021-07-29 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_build', '0006_auto_20210729_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnailimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
