# Generated by Django 3.1.7 on 2021-07-29 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ace_build', '0007_auto_20210729_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimization',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
